-- fedora-buchhwin-hyprland — main Hyprland configuration
--
-- Hyprland 0.55 replaced hyprlang with Lua ("Since Hyprland 0.55, hyprlang is
-- deprecated in favor of lua"). Every dotfile collection you will find online
-- is still the old `bind = SUPER, Q, killactive` syntax and will not load here.
--
-- Layout of this directory:
--   hyprland.lua       this file — structure, reads the other three
--   settings.lua       your values, owned by the settings GUI (not in git)
--   theme.lua          colours, generated by theme/apply-theme.py
--   binds.lua          how a bind entry becomes a real key binding
--   rules.lua          window and workspace rules
--
-- The split exists so the GUI never has to parse hand-written Lua: it only
-- ever rewrites settings.lua, which is plain data.

package.path = os.getenv("HOME") .. "/.config/hypr/?.lua;" .. package.path

local ok_settings, S = pcall(require, "settings")
if not ok_settings then
    -- A broken settings.lua must not leave you without a desktop: fall back to
    -- the shipped example so the session still starts and can be repaired.
    S = dofile(os.getenv("HOME") .. "/.config/hypr/settings.example.lua")
end

local ok_theme, T = pcall(require, "theme")
if not ok_theme then
    T = { border_active = "rgba(cba6f7ff)", border_inactive = "rgba(313244aa)",
          shadow_color = 0xee11111b, hex = {} }
end

local look = S.look or {}
local prof = look.profile or "work"

-- The showcase profile is the same configuration turned up, not a second
-- config: slower animations, more blur, deeper shadows. One click in the GUI.
local showcase = (prof == "showcase")

------------------------------------------------------------------------------
-- Monitors
------------------------------------------------------------------------------
if S.monitors and #S.monitors > 0 then
    for _, m in ipairs(S.monitors) do
        hl.monitor({
            output   = m.output or "",
            mode     = m.mode or "preferred",
            position = m.position or "auto",
            scale    = m.scale or "auto",
        })
    end
else
    hl.monitor({ output = "", mode = "preferred", position = "auto", scale = "auto" })
end

------------------------------------------------------------------------------
-- Environment
------------------------------------------------------------------------------
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("XCURSOR_THEME", "catppuccin-" .. ((S.theme or {}).flavour or "mocha") .. "-dark-cursors")

------------------------------------------------------------------------------
-- Look and feel
------------------------------------------------------------------------------
hl.config({
    general = {
        gaps_in     = look.gaps_in or 5,
        gaps_out    = look.gaps_out or 12,
        border_size = look.border_size or 2,

        col = {
            active_border   = T.border_active,
            inactive_border = T.border_inactive,
        },

        resize_on_border = true,
        allow_tearing    = false,
        layout           = "dwindle",
    },

    decoration = {
        rounding       = look.rounding or 12,
        rounding_power = 2,

        active_opacity   = look.active_opacity or 1.0,
        inactive_opacity = look.inactive_opacity or 0.94,

        shadow = {
            enabled      = look.shadow ~= false,
            range        = showcase and 24 or (look.shadow_range or 12),
            render_power = 3,
            color        = T.shadow_color,
        },

        blur = {
            enabled    = look.blur ~= false,
            size       = showcase and 10 or (look.blur_size or 6),
            passes     = showcase and 3 or (look.blur_passes or 2),
            vibrancy   = 0.1696,
            noise      = 0.012,
            -- Blur the bar, menus and notifications; windows keep their own
            -- background. This is the setting that decides whether the desktop
            -- feels light or heavy.
            popups     = true,
            special    = false,
        },
    },

    animations = { enabled = look.animations ~= false },

    dwindle = {
        preserve_split = true,
        smart_split    = false,
        smart_resizing = true,
    },

    master = { new_status = "master" },

    misc = {
        force_default_wallpaper   = 0,
        disable_hyprland_logo     = true,
        disable_splash_rendering  = true,
        vfr                       = true,   -- do not redraw a still screen
        focus_on_activate         = true,
        new_window_takes_over_fullscreen = 2,
    },

    input = {
        kb_layout    = (S.input or {}).kb_layout or "us",
        kb_variant   = (S.input or {}).kb_variant or "",
        kb_options   = (S.input or {}).kb_options or "",
        follow_mouse = (S.input or {}).follow_mouse or 1,
        sensitivity  = (S.input or {}).sensitivity or 0,
        accel_profile = (S.input or {}).accel_profile or "adaptive",
        repeat_rate  = (S.input or {}).repeat_rate or 40,
        repeat_delay = (S.input or {}).repeat_delay or 300,

        touchpad = {
            natural_scroll     = (S.input or {}).natural_scroll ~= false,
            tap_to_click       = (S.input or {}).tap_to_click ~= false,
            disable_while_typing = true,
            scroll_factor      = 0.6,
        },
    },
})

------------------------------------------------------------------------------
-- Animation curves
--
-- Springs rather than beziers: they settle instead of stopping dead, which is
-- what makes motion read as smooth in a screen recording. Everything stays
-- under ~200 ms — visible, never in the way.
------------------------------------------------------------------------------
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1} } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1} } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1} } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1} } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1} } })
hl.curve("snappy",         { type = "spring", mass = 1, stiffness = 330, dampening = 26 })
hl.curve("gentle",         { type = "spring", mass = 1, stiffness = 210, dampening = 24 })

local sp = showcase and 0.6 or 1.0     -- showcase: slower, for recordings

hl.animation({ leaf = "global",        enabled = look.animations ~= false, speed = 7 * sp, bezier = "quick" })
hl.animation({ leaf = "windows",       enabled = true, speed = 6.0 * sp, spring = "snappy" })
hl.animation({ leaf = "windowsIn",     enabled = true, speed = 6.0 * sp, spring = "snappy", style = "popin 92%" })
hl.animation({ leaf = "windowsOut",    enabled = true, speed = 6.5 * sp, bezier = "quick",  style = "popin 92%" })
hl.animation({ leaf = "border",        enabled = true, speed = 5.0 * sp, bezier = "easeOutQuint" })
hl.animation({ leaf = "fade",          enabled = true, speed = 6.0 * sp, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true, speed = 5.5 * sp, spring = "gentle" })
hl.animation({ leaf = "layersIn",      enabled = true, speed = 5.5 * sp, spring = "gentle", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true, speed = 6.5 * sp, bezier = "quick",  style = "fade" })
hl.animation({ leaf = "workspaces",    enabled = true, speed = 5.5 * sp, spring = "gentle", style = "slidefade 15%" })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 6.0 * sp, spring = "snappy", style = "slidevert" })

------------------------------------------------------------------------------
-- Gestures
------------------------------------------------------------------------------
hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })
hl.gesture({ fingers = 4, direction = "up",         action = "special" })

------------------------------------------------------------------------------
-- Bindings and rules
------------------------------------------------------------------------------
require("binds")
require("rules")

------------------------------------------------------------------------------
-- Autostart
--
-- The background services (bar, notifications, clipboard, wallpaper, idle,
-- polkit) are systemd user units, not exec-once lines: they restart on crash
-- and their logs land in the journal. Only the extras from settings.lua are
-- started here.
------------------------------------------------------------------------------
hl.on("hyprland.start", function()
    for _, cmd in ipairs(S.autostart or {}) do
        hl.exec_cmd(cmd)
    end
end)
