-- fedora-buchhwin-hyprland — main Hyprland configuration
--
-- Hyprland 0.55 replaced hyprlang with Lua ("Since Hyprland 0.55, hyprlang is
-- deprecated in favor of lua"). Every dotfile collection you will find online
-- is still the old `bind = SUPER, Q, killactive` syntax and will not load here.
--
-- Layout of this directory:
--   hyprland.lua       this file — structure, reads the other three
--   settings.lua       your values, owned by the settings GUI (not in git)
--   theme.lua          colours, generated by theme/apply-theme.py
--   binds.lua          how a bind entry becomes a real key binding
--   rules.lua          window and workspace rules
--
-- The split exists so the GUI never has to parse hand-written Lua: it only
-- ever rewrites settings.lua, which is plain data.

package.path = os.getenv("HOME") .. "/.config/hypr/?.lua;" .. package.path

local ok_settings, S = pcall(require, "settings")
if not ok_settings then
    -- A broken settings.lua must not leave you without a desktop: fall back to
    -- the shipped example so the session still starts and can be repaired.
    S = dofile(os.getenv("HOME") .. "/.config/hypr/settings.example.lua")
end

local ok_theme, T = pcall(require, "theme")
if not ok_theme then
    T = { border_active = "rgba(cba6f7ff)", border_inactive = "rgba(313244aa)",
          shadow_color = 0xee11111b, hex = {} }
end

local look   = S.look or {}
local layout = S.layout or {}
local prof   = look.profile or "work"

-- The showcase profile is the same configuration turned up, not a second
-- config: slower animations, more blur, deeper shadows. One click in the GUI.
local showcase = (prof == "showcase")

------------------------------------------------------------------------------
-- Monitors
------------------------------------------------------------------------------
-- Screens are addressed by DESCRIPTION ("desc:Dell Inc. U2720Q"), not by
-- DP-1/HDMI-A-1. Connector names change the moment a cable moves; the
-- description does not — otherwise the whole arrangement is wrong after
-- unplugging something once.
--
-- The catch-all entry stays LAST so any screen not listed still lights up
-- instead of staying black.
--- The field names come from Hyprland's own type stubs,
--- /usr/share/hypr/stubs/hl.meta.lua, class HL.MonitorSpec — which documents the
--- whole Lua API and is a far better source than the wiki for exactly this.
--- Note it is `disabled`, not `enabled`.
for _, m in ipairs(S.monitors or {}) do
    local out = m.desc and ("desc:" .. m.desc) or (m.output or "")
    if m.enabled == false then
        hl.monitor({ output = out, disabled = true })
    else
        local spec = {
            output   = out,
            mode     = m.mode or "preferred",
            position = m.position or "auto",
            scale    = m.scale or "auto",
        }
        --- Only written when the settings actually carry one. Tested against nil
        --- and not with `m.transform and ...`, because 0 and false are both
        --- meaningful values here and both are falsy in Lua — the same trap that
        --- once turned every switched-off setting into nil.
        if m.transform ~= nil then spec.transform = m.transform end
        if m.vrr ~= nil then spec.vrr = m.vrr end
        if m.bitdepth ~= nil then spec.bitdepth = m.bitdepth end
        if m.mirror and m.mirror ~= "" and m.mirror ~= "none" then
            spec.mirror = m.mirror
        end
        hl.monitor(spec)
    end
end
--- The catch-all. `scale` is settable because "auto" is a guess derived from the
--- EDID physical size, and inside a virtual machine that size is fiction — it
--- comes from the hypervisor, not from a panel. A VM that reports nonsense gets
--- scale 2 and every element on screen doubles. Phase 80 sets this to 1 there;
--- the Displays page overrides it per screen either way.
hl.monitor({ output = "", mode = "preferred", position = "auto",
             scale = S.monitor_scale or "auto" })

------------------------------------------------------------------------------
-- Environment
------------------------------------------------------------------------------
-- The pointer is settable, because it is the one piece of the look you stare
-- at all day. Default is KDE's dark Breeze: the package ships exactly two
-- themes, "breeze_cursors" and "Breeze_Light", so the dark one is the plain
-- name — there is no "Breeze_Dark", however much it looks like there should be.
local cursor_size  = tostring(look.cursor_size or 24)
local cursor_theme = look.cursor_theme or "breeze_cursors"
hl.env("XCURSOR_SIZE", cursor_size)
hl.env("HYPRCURSOR_SIZE", cursor_size)
hl.env("XCURSOR_THEME", cursor_theme)
-- HYPRCURSOR_THEME was missing while HYPRCURSOR_SIZE was set, so hyprcursor —
-- which Hyprland prefers over XCursor when it finds a theme — got a size and no
-- name. Setting only half of a pair is worse than setting neither.
hl.env("HYPRCURSOR_THEME", cursor_theme)

------------------------------------------------------------------------------
-- Look and feel
------------------------------------------------------------------------------
hl.config({
    general = {
        gaps_in     = look.gaps_in or 5,
        gaps_out    = look.gaps_out or 12,
        border_size = look.border_size or 2,

        col = {
            active_border   = T.border_active,
            inactive_border = T.border_inactive,
        },

        -- Off by default, and that is deliberate. Hyprland pairs this with
        -- extend_border_grab_area (15px), so the resize handle reaches well
        -- past the visible border and straight over the close button of any
        -- client-side-decorated window. Aiming for that button then drags the
        -- window instead of pressing it, which is exactly as maddening as it
        -- sounds. Resizing with the mouse still works on SUPER + right-drag
        -- (see binds.lua), and the keyboard snaps are untouched.
        resize_on_border = layout.resize_on_border == true,
        -- Master switch only. Nothing tears until a window rule asks for it,
        -- and the only rules that do are the games in rules.lua — where a torn
        -- frame beats a late one. Every other window is unaffected.
        allow_tearing    = layout.allow_tearing ~= false,
        layout           = layout.default or "dwindle",

        -- Magnetic snapping for FLOATING windows: drag one near an edge or
        -- near another window and it clicks into place. This is what makes a
        -- floating workspace feel deliberate rather than sloppy.
        --
        -- It is NOT Windows' "drag to the edge to fill half the screen" —
        -- Hyprland has no such thing. That lives in scripts/snap.py, on the
        -- arrow keys.
        snap = {
            enabled      = layout.snap ~= false,
            window_gap   = layout.snap_window_gap or 12,
            monitor_gap  = layout.snap_monitor_gap or 12,
            respect_gaps = true,
        },
    },

    decoration = {
        rounding       = look.rounding or 12,
        rounding_power = 2,

        active_opacity   = look.active_opacity or 1.0,
        inactive_opacity = look.inactive_opacity or 0.94,

        shadow = {
            enabled      = look.shadow ~= false,
            range        = showcase and 24 or (look.shadow_range or 12),
            render_power = 3,
            color        = T.shadow_color,
        },

        blur = {
            enabled    = look.blur ~= false,
            size       = showcase and 10 or (look.blur_size or 6),
            passes     = showcase and 3 or (look.blur_passes or 2),
            vibrancy   = 0.1696,
            noise      = 0.012,
            -- Blur the bar, menus and notifications; windows keep their own
            -- background. This is the setting that decides whether the desktop
            -- feels light or heavy.
            popups     = true,
            special    = false,
        },
    },

    animations = { enabled = look.animations ~= false },

    dwindle = {
        preserve_split = true,
        smart_split    = false,
        smart_resizing = true,
    },

    master = { new_status = "master" },

    -- Games are the reason this block exists. Most of them are X11 — Minecraft
    -- included — and on a scaled display XWayland hands them the wrong size,
    -- so "fullscreen" ends up as a blurry window that does not cover the
    -- screen. force_zero_scaling gives them the real pixel grid instead.
    --
    -- use_nearest_neighbor is Hyprland's default and stays: scaled X11 windows
    -- look crisp rather than smeared. Turn it off only if some app looks
    -- jagged, not because a wiki page said so.
    xwayland = {
        force_zero_scaling = true,
    },

    -- Hyprland's own popups. The update notice appears in the middle of the
    -- screen after every version bump, and the donation nag twice a year.
    -- Neither belongs in a desktop somebody else installed: the first thing a
    -- new user would see is a dialog about a component they did not choose.
    -- Support Hyprland, just not by ambushing the person who ran our installer.
    ecosystem = {
        no_update_news   = true,
        no_donation_nag  = true,
    },

    misc = {
        force_default_wallpaper   = 0,
        disable_hyprland_logo     = true,
        disable_splash_rendering  = true,

        -- The third of Hyprland's own popups, and the only one that is RED:
        -- "Hyprland was started without start-hyprland. This is highly not
        -- recommended unless you are in a debugging environment." It greeted
        -- every login on a fresh install — seen in a screenshot of one, not
        -- reasoned about.
        --
        -- The session is started by uwsm (`uwsm start -S -F /usr/bin/Hyprland`
        -- in hyprland-buchhwin.desktop), which is the supported way to run
        -- Hyprland under systemd and the reason wayland-wm@Hyprland.service
        -- exists at all. start-hyprland is the OTHER supported launcher; it
        -- supplies a watchdog file descriptor that uwsm does not. Running both
        -- session managers to silence a warning would be the wrong trade, so
        -- the warning is switched off instead.
        --
        -- Name taken from `hyprctl descriptions -j` on the running 0.55.4, not
        -- from a wiki: "whether to disable the warning about not using
        -- start-hyprland", default false.
        disable_watchdog_warning  = true,

        -- If hyprlock dies while the screen is locked, the compositor stays
        -- locked — by design, so that killing the lock client is not a way in.
        -- The cost is that a crashed lock screen leaves you staring at
        -- Hyprland's "lockscreen app died" notice with no way back except a
        -- reboot, losing whatever was open. This lets a fresh lock client
        -- attach to the existing lock instead. It still demands your password;
        -- what it does not demand is a reboot.
        allow_session_lock_restore = true,
        focus_on_activate         = true,
        -- Renamed in 0.55; same 0/1/2 meaning as the old
        -- new_window_takes_over_fullscreen. 2 is already the default, kept
        -- explicit so the intent is readable.
        on_focus_under_fullscreen = 2,
        -- VFR is not a misc key any more. It lives at debug:vfr, defaults to
        -- true and is documented as "do not turn off unless debugging", so
        -- there is nothing for us to set.
    },

    input = {
        kb_layout    = (S.input or {}).kb_layout or "us",
        kb_variant   = (S.input or {}).kb_variant or "",
        kb_options   = (S.input or {}).kb_options or "",
        follow_mouse = (S.input or {}).follow_mouse or 1,
        sensitivity  = (S.input or {}).sensitivity or 0,
        accel_profile = (S.input or {}).accel_profile or "adaptive",
        repeat_rate  = (S.input or {}).repeat_rate or 40,
        repeat_delay = (S.input or {}).repeat_delay or 300,

        touchpad = {
            natural_scroll     = (S.input or {}).natural_scroll ~= false,
            tap_to_click       = (S.input or {}).tap_to_click ~= false,
            disable_while_typing = true,
            scroll_factor      = 0.6,
        },
    },
})

------------------------------------------------------------------------------
-- Animation curves
--
-- Springs rather than beziers: they settle instead of stopping dead, which is
-- what makes motion read as smooth in a screen recording. Everything stays
-- under ~200 ms — visible, never in the way.
------------------------------------------------------------------------------
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1} } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1} } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1} } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1} } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1} } })
hl.curve("snappy",         { type = "spring", mass = 1, stiffness = 330, dampening = 26 })
hl.curve("gentle",         { type = "spring", mass = 1, stiffness = 210, dampening = 24 })
-- A window arriving with the faintest overshoot, and menus that settle rather
-- than stop. Both are springs, because a bezier of the same duration reads as
-- mechanical: it decelerates to exactly zero and holds, and the eye notices.
-- Overshoot is kept small on purpose — a window that visibly bounces is a
-- demo, not something to work in front of all day.
hl.curve("arrive",         { type = "spring", mass = 1, stiffness = 380, dampening = 24 })
hl.curve("settle",         { type = "spring", mass = 0.9, stiffness = 250, dampening = 22 })
-- Leaving is faster than arriving. A window you have closed is already gone as
-- far as you are concerned, and waiting for it feels like lag; a window
-- appearing is worth 150 ms because it tells you where it came from.
hl.curve("leave",          { type = "bezier", points = { {0.4, 0},     {1, 1} } })

local sp = showcase and 0.6 or 1.0     -- showcase: slower, for recordings

hl.animation({ leaf = "global",        enabled = look.animations ~= false, speed = 7 * sp, bezier = "quick" })
hl.animation({ leaf = "windows",       enabled = true, speed = 6.0 * sp, spring = "arrive" })
-- popin 90%: the window grows the last tenth of the way in, which reads as
-- "this opened here" rather than "this was always here and faded up".
hl.animation({ leaf = "windowsIn",     enabled = true, speed = 5.6 * sp, spring = "arrive", style = "popin 90%" })
hl.animation({ leaf = "windowsOut",    enabled = true, speed = 7.5 * sp, bezier = "leave",  style = "popin 92%" })
hl.animation({ leaf = "windowsMove",   enabled = true, speed = 6.0 * sp, spring = "settle" })
hl.animation({ leaf = "border",        enabled = true, speed = 5.0 * sp, bezier = "easeOutQuint" })
-- The border glow follows the focus rather than snapping with it: it is the
-- one animation whose whole job is to draw the eye to where focus went.
hl.animation({ leaf = "borderangle",   enabled = true, speed = 4.0 * sp, bezier = "easeInOutCubic" })
hl.animation({ leaf = "fade",          enabled = true, speed = 6.5 * sp, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true, speed = 5.5 * sp, spring = "settle" })
-- Menus and popups slide a hair out of the edge they belong to. 8% is small
-- enough to read as "it came from the bar" without any travel to sit through.
hl.animation({ leaf = "layersIn",      enabled = true, speed = 5.2 * sp, spring = "settle", style = "slidefade top 8%" })
hl.animation({ leaf = "layersOut",     enabled = true, speed = 7.5 * sp, bezier = "leave",  style = "fade" })
hl.animation({ leaf = "workspaces",    enabled = true, speed = 5.2 * sp, spring = "settle", style = "slidefade 12%" })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 6.5 * sp, spring = "arrive", style = "slidevert" })

------------------------------------------------------------------------------
-- Gestures
------------------------------------------------------------------------------
hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })
hl.gesture({ fingers = 4, direction = "up",         action = "special" })
-- Three fingers down closes, four fingers horizontally moves the window with
-- you. Both are what a trackpad user reaches for without being told.
hl.gesture({ fingers = 3, direction = "down",       action = "close" })
hl.gesture({ fingers = 4, direction = "horizontal", action = "move" })

------------------------------------------------------------------------------
-- Bindings and rules
------------------------------------------------------------------------------
require("binds")
require("rules")

------------------------------------------------------------------------------
-- Autostart
--
-- The background services (bar, notifications, clipboard, wallpaper, idle,
-- polkit) are systemd user units, not exec-once lines: they restart on crash
-- and their logs land in the journal. Only the extras from settings.lua are
-- started here.
------------------------------------------------------------------------------
hl.on("hyprland.start", function()
    for _, cmd in ipairs(S.autostart or {}) do
        hl.exec_cmd(cmd)
    end
end)
