#!/usr/bin/env python3
"""Generate docs/DEFAULTS.md from the settings themselves.

The point of generating it is that a hand-written table of "which program opens
what" is wrong within a month and nobody notices, because nothing checks it.
This reads the same files the desktop reads, so the document cannot disagree
with the system it describes.

    gen-defaults-doc.py            write docs/DEFAULTS.md
    gen-defaults-doc.py --check    exit 1 if it is out of date (for CI)
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
EXAMPLE = REPO / "dotfiles" / "hypr" / "settings.example.lua"
MIMEAPPS = REPO / "dotfiles" / "mimeapps.list"
TARGET = REPO / "docs" / "DEFAULTS.md"

HEADER = """<!-- GENERATED by scripts/gen-defaults-doc.py — do not edit by hand. -->
# Default applications

Everything here comes from the shipped settings, so it cannot drift out of step
with what the desktop actually does. Change any of it in the settings app, or
in `~/.config/hypr/settings.lua`.

"""


def lua_table(name: str) -> dict[str, str]:
    """Pull one flat `name = { key = "value", ... }` table out of the example.

    Deliberately a small regex rather than a Lua parser: the example file is
    plain data by design, and pulling in a parser to read four string fields
    would be a dependency nobody could justify.
    """
    text = EXAMPLE.read_text()
    match = re.search(rf"^\s*{name}\s*=\s*\{{(.*?)^\s*\}},", text,
                      re.S | re.M)
    if not match:
        return {}
    out: dict[str, str] = {}
    for line in match.group(1).splitlines():
        entry = re.match(r"\s*([a-z_]+)\s*=\s*\"([^\"]*)\"", line)
        if entry:
            out[entry.group(1)] = entry.group(2)
    return out


def keybind_rows() -> list[tuple[str, str]]:
    """The bindings that launch a program, in the order they are listed."""
    text = EXAMPLE.read_text()
    rows = []
    for m in re.finditer(r'\{\s*key\s*=\s*"([^"]+)".*?arg\s*=\s*"@(\w+)".*?desc\s*=\s*"([^"]*)"',
                         text):
        key, token, desc = m.groups()
        if token in ("terminal", "browser", "file_manager", "editor", "launcher"):
            rows.append((key, desc))
    return rows


def mime_rows() -> list[tuple[str, str]]:
    if not MIMEAPPS.exists():
        return []
    rows = []
    for line in MIMEAPPS.read_text().splitlines():
        if "=" not in line or line.startswith("["):
            continue
        mime, app = line.split("=", 1)
        rows.append((mime.strip(), app.strip().removesuffix(".desktop")))
    return rows


def installed(command: str) -> str:
    """A tick when the program is actually on this machine."""
    binary = command.split()[0]
    found = subprocess.run(["command", "-v", binary], capture_output=True,
                           shell=False, check=False)
    return "" if found.returncode else ""


def render() -> str:
    out = [HEADER]

    programs = lua_table("programs")
    if programs:
        out.append("## Programs\n\n| Role | Program |\n|---|---|\n")
        labels = {
            "terminal": "Terminal", "browser": "Browser",
            "file_manager": "File manager", "editor": "Editor",
            "launcher": "Launcher", "calendar": "Calendar", "mail": "Mail",
            "image_viewer": "Images", "music": "Music",
        }
        for key, value in programs.items():
            out.append(f"| {labels.get(key, key)} | `{value}` |\n")
        out.append("\n")

    binds = keybind_rows()
    if binds:
        out.append("## How to reach them\n\n| Keys | Opens |\n|---|---|\n")
        for key, desc in binds:
            out.append(f"| `{key}` | {desc} |\n")
        out.append("\n")

    mimes = mime_rows()
    if mimes:
        out.append("## File types\n\n| Type | Opens with |\n|---|---|\n")
        for mime, app in mimes:
            out.append(f"| `{mime}` | {app} |\n")
        out.append("\n")

    out.append(
        "## Changing them\n\n"
        "Settings → Defaults, or edit `programs` in `~/.config/hypr/settings.lua`.\n"
        "The key bindings refer to roles (`@browser`), never to a program name,\n"
        "so switching your browser is one edit in one place.\n")
    return "".join(out)


def main() -> int:
    content = render()
    if "--check" in sys.argv:
        current = TARGET.read_text() if TARGET.exists() else ""
        if current != content:
            print(f"{TARGET} is out of date — run scripts/gen-defaults-doc.py",
                  file=sys.stderr)
            return 1
        print(f"  {TARGET.name} is up to date")
        return 0

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(content)
    print(f"  wrote {TARGET.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
