#!/usr/bin/env bash
#
# idle-config.sh — write ~/.config/hypr/hypridle.conf from settings.lua.
#
#   idle-config.sh            generate the file and restart the idle manager
#   idle-config.sh --print    write nothing, print what would be generated
#
# hypridle cannot read settings.lua, so the file has to be generated — the same
# arrangement scripts/dock.py already uses for the dock's waybar config. Before
# this existed, ~/.config/hypr/hypridle.conf was a symlink into the repository,
# and the four timings on the settings app's Power page were written to
# settings.lua and read by nobody at all. Every slider moved, saved, and
# changed nothing.
#
# A value of 0 removes that step entirely rather than writing `timeout = 0`,
# which hypridle would fire on immediately.
set -euo pipefail

REPO="${BUCHHWIN_REPO:-${XDG_DATA_HOME:-$HOME/.local/share}/fedora-buchhwin-hyprland}"
[[ -d "$REPO" ]] || REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONF="${XDG_CONFIG_HOME:-$HOME/.config}/hypr/hypridle.conf"

get() { python3 "$REPO/scripts/settings.py" get "$1" 2>/dev/null || true; }

seconds() {
    # seconds <dotted.key> <default> — a non-number (a missing key prints
    # "None") falls back instead of writing a broken listener.
    local value; value="$(get "$1")"
    [[ "$value" =~ ^[0-9]+$ ]] && { printf '%s' "$value"; return 0; }
    printf '%s' "$2"
}

# Read once. Each call starts python AND the lua interpreter, so asking twice
# for the same number is a tenth of a second nobody gets back.
DIM="$(seconds idle.dim_after 300)"
LOCK="$(seconds idle.lock_after 600)"
BLANK="$(seconds idle.screen_off 900)"
SUSPEND="$(seconds idle.suspend_after 0)"

# The dispatcher call, in Lua.
#
# `hyprctl dispatch dpms off` — the form every tutorial and every hypridle
# example still shows — is a Lua SYNTAX ERROR under the Lua config provider,
# and hyprctl prints it to stdout and exits 0. So the screen simply never
# blanked, nothing failed, and nothing said so. Measured against the running
# 0.55.4:
#
#   $ `hyprctl dispatch dpms on`
#   error: [string "return hl.dispatch(dpms on)"]:1: ')' expected near 'on'
#   $ echo $?
#   0
#
# The shape below is not guesswork either: hl.dsp carries `dpms`, and
# ConfigActions.hpp declares dpms(eTogglableAction, optional<PHLMONITOR>) with
# the field named `action` (LuaBindingsInternal.hpp, tableToggleAction).
#
# ⚠️ A missing or misspelled action means TOGGLE, not an error — a typo here
# blanks the screen instead of complaining. hypridle passes the whole line to a
# shell and keeps the braces intact; that was tested before relying on it.
dpms() { printf "hyprctl dispatch 'hl.dsp.dpms({ action = \"%s\" })'" "$1"; }

listener() {
    # listener <timeout> <on-timeout> [on-resume]
    (( $1 > 0 )) || return 0
    printf '\nlistener {\n    timeout = %s\n    on-timeout = %s\n' "$1" "$2"
    [[ -n "${3:-}" ]] && printf '    on-resume = %s\n' "$3"
    printf '}\n'
}

generate() {
    cat <<EOF
# GENERATED by scripts/idle-config.sh — every "Apply" in the settings app
# overwrites this file. Change the timings under Settings → Power, or with
#   bhctl set idle.lock_after=900
# The defaults live in dotfiles/hypr/hypridle.conf, which is the template.

general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = $(dpms on)
    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
}
EOF

    # Dim first, so the screen warns before it locks.
    #
    # -c backlight, and a percentage. Without the class, brightnessctl picks
    # whatever device it considers current, which on a machine with no screen
    # backlight is an LED — measured in a VM, it answered
    # `input1::numlock,leds,0,0%,1`, so the dim step would have turned down the
    # keyboard's num-lock light. Without the %, `set 10` is a RAW value: 10% on
    # a panel whose maximum is 100, and effectively off on one whose maximum is
    # 19200.
    listener "$DIM" "brightnessctl -c backlight -s set 10%" "brightnessctl -c backlight -r"
    listener "$LOCK" "loginctl lock-session"
    listener "$BLANK" "$(dpms off)" "$(dpms on)"

    # Suspend needs no ordering against the lock step: before_sleep_cmd locks
    # the session on the way down whatever the timings say, so even a suspend
    # timeout shorter than the lock timeout cannot leave a machine asleep and
    # unlocked.
    listener "$SUSPEND" "systemctl suspend"
}

if [[ "${1:-}" == "--print" ]]; then
    generate
    exit 0
fi

mkdir -p "$(dirname "$CONF")"

# Installations from before this script existed have a symlink here that points
# straight into the cloned repository. Writing through it would put machine
# state into a git checkout, so it goes first — the same cleanup that
# lib/80-vm-tweaks.sh does for a stale env-hyprland.
[[ -L "$CONF" ]] && rm -f "$CONF"

# Written beside the target and moved into place: hypridle watches this file,
# and a half-written config is one it can fail to parse.
tmp="$(mktemp "$CONF.XXXXXX")"
trap 'rm -f "$tmp"' EXIT
generate >"$tmp"
chmod 0644 "$tmp"
mv -f "$tmp" "$CONF"
trap - EXIT

# try-restart, NOT restart: outside a graphical session this must not start an
# idle manager that would then lock a machine nobody is sitting at.
systemctl --user try-restart buchhwin-idle.service 2>/dev/null || true

printf '  hypridle: dim %ss, lock %ss, screen off %ss, suspend %ss (0 = that step is off)\n' \
    "$DIM" "$LOCK" "$BLANK" "$SUSPEND"
